// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alammewoggxtuykkltcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYW1tZXdvZ2d4dHV5a2tsdGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjUwMTksImV4cCI6MjA2NzA0MTAxOX0.ajOfJMAF4HYNnMPxf3TAK9uBlA288yKMEzZIghVnNpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);